version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./volumes/db:/var/lib/mysql
    # ports:
    #   - 33062:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dummy_pwd
  bot:
    build:
      context: .
      dockerfile: ./docker.images/bot.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./volumes/config/app.yml:/app/config/app.yml
      - ./volumes/config/database.yml:/app/config/database.yml
      - ./volumes/config/secrets.yml:/app/config/secrets.yml
      - ./volumes/log:/app/log
  web:
    build:
      context: .
      dockerfile: ./docker.images/web.Dockerfile
    ports:
      - 3099:3000
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./volumes/config/app.yml:/app/config/app.yml
      - ./volumes/config/database.yml:/app/config/database.yml
      - ./volumes/config/secrets.yml:/app/config/secrets.yml
      - ./volumes/log:/app/log
